### ISSUE TITLE
Player instantly dies on join

### ISSUE THREAD

**Issue by YannickGTHD** [xxshady/altv-custom-player-death#1]
I don't know if there is something wrong on my side, but directly on Player-Spawn after joining the the server, the player dies. 
I changed noting and just loaded your resource. Any attemps to fix that, didn't worked for me. Any ideas?

**Comment by xxshady** [comment]
Do you spawn player using `spawnPlayer` function? like in the usage-example
https://github.com/xxshady/altv-custom-player-death/blob/d15c4ccdd7eb5657ffcef03892c67843bf7ea48b/server/usage-example.js#L11

**Comment by YannickGTHD** [comment]
I'm just using the example for now, thats why I said I changed nothing.

**Comment by xxshady** [comment]
do you use resource restart?

**Comment by xxshady** [comment]
and on what alt:V branch do you try it?

**Comment by YannickGTHD** [comment]
nope, restarting the server every time, restart resources creates more problems than it solves. 

alt:V Server 13.38 (release) 
latest.

**Comment by xxshady** [comment]
it works fine for me, idk

<img src="https://user-images.githubusercontent.com/54737754/212479331-b17113a5-7cbd-4b68-a74f-590da5d5086c.png" width=300 />

**Comment by YannickGTHD** [comment]
Thanks for checking! I think I have to dig into my code again. Something else is wrong then :/
